AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: 'AWS CloudFormation Lambda Function Container'

Parameters:
  StageName:
    Type: String
    Default: dev
  Region:
    Type: String
    Default: us-east-1
  AcmCertificateArn:
    Type: String
    Description: The ARN of the SSL certificate to use for the CloudFront distribution.
    Default: arn:aws:acm:us-east-1:983510677257:certificate/da5bbe33-631c-407c-ac1f-caab6c21c1f2
  ImageURI:
    Type: String
    Default: will-be-replaced-by-sed

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Domain:
        DomainName: lambda-container.gagnonagon.com
        CertificateArn: !Ref AcmCertificateArn
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: Z02078493KG1I0U5VKXFC

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-container-function
      PackageType: Image
      ImageUri: !Ref ImageURI
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  Endpoint: 
    Description: Endpoint for Lambda Function.
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${Region}.amazonaws.com/${StageName}/"